services:
  gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./gateway_service/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth-service
      - users-service
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mehdi
      POSTGRES_DB: postgres 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  auth-service:
    build:
      context: .
      dockerfile: GenericPyService.Dockerfile
      args:
        - SERVICE_DIR=auth_service
    environment:
      - DATABASE_URL=postgresql://user:mehdi@db:5432/auth_db
      - FLASK_ENV=development 
    volumes:
      - ./auth_service/app:/app # Hot-reloading
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  users-service:
    build:
      context: .
      dockerfile: GenericPyService.Dockerfile
      args:
        - SERVICE_DIR=users_service
    environment:
      - DATABASE_URL=postgresql://user:mehdi@db:5432/users_db
      - FLASK_ENV=development
    volumes:
      - ./users_service/app:/app # Hot-reloading
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./frontend/userPage
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
