server {
    listen 80;
    server_name localhost mehdidev.xyz;

    location / {
        proxy_pass http://frontend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/auth/ {
        proxy_pass http://auth-service:5000/public/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/users/ {
        proxy_pass http://users-service:5000/public/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/posts/ {
        client_max_body_size 50M;

        proxy_pass http://posts-service:5000/public/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/media/posts/ {
        # rewrite /api/media/posts/file.jpg to /posts/file.jpg for MinIO
        rewrite ^/api/media/posts/(.*)$ /posts/$1 break;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://minio:9000;
    }

    location /api/media/profiles/ {
        # rewrite /api/media/profiles/file.jpg to /profiles/file.jpg for MinIO
        rewrite ^/api/media/profiles/(.*)$ /profiles/$1 break;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://minio:9000;
    }

    location /socket.io/ {
        proxy_pass http://messages-service:5000; # Internal port of your Flask container
        
        # Essential WebSocket headers
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        
        # Pass the real IP to the backend so you know who is connecting
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Disable buffering for real-time performance
        proxy_buffering off;
    }

    location /health {
        return 200 "OK";
    }
}
